### ISSUE TITLE
Chapter 4 queue storage example

### ISSUE THREAD

**Issue by cdimicel** [fouldsy/azure-mol-samples-2nd-ed#4]
Azure seems to have changed QueueService to QueueServiceClient, so the queue storage example does not run.  QueueServiceClient also needs an account_url parameter.

**Comment by fouldsy** [comment]
So long as you use the versioned Python library as noted in text and https://github.com/fouldsy/azure-mol-samples-2nd-ed/blob/master/04/README.md, the sample should work as-is.

Yes, the underlying SDK has changed, but this is designed to just be a simple example to show queues in action. It can be updated to work, but again, this is meant to just let you see queues in action rather than as a for-real example of using it for your own code. azurerm wouldn't be the way to do that anyway - you'd natively use the Python SDK which now lets you interact with Storage Queues and Storage Tables.

**Comment by cdimicel** [comment]
Cool.  Thanks for the reply.
